#!/bin/bash
printenv | sed 's/^\(.*\)$/export \1/g' > /env.sh

echo "{\"api\":\"_simpleauth_sess=\\\"${HB_API_KEY}\\\"\",\"platform\":\"${HB_PLATFORM}\",\"location\":\"${TROVE_DATA}\"}" > ${TROVE_CONFIG}/config.json